# Generated by Django 3.2 on 2023-04-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(),
        ),
    ]
