# Generated by Django 3.2 on 2023-04-13 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_title', to='reviews.genre'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_genre', to='reviews.title'),
        ),
    ]
